### ISSUE TITLE
Possibly improve flashing performance

### ISSUE THREAD

**Issue by tetsuo55** [timduru/device_asus_tf_unified#4]
Hello timduru,

On msm platforms we have been using the following 2 commits to overcome some performance issues while flashing.
Maybe these changes will apply to our devices too?

https://github.com/airlessproject/android_device_sony_fusion3-common/commit/c7ddaba91eb90f4faf381eebc9a2b4a05f444f5f

https://github.com/airlessproject/android_device_sony_fusion3-common/commit/a8b8bb19156611d93daa36bbc3b97348455ff54d

Would you be so kind to test this and see if it helps?

**Comment by timduru** [comment]
that'd be for TWRP I think, I've not really built a custom TWRP yet so can't really test.
