### ISSUE TITLE
persist.tegra.nvmmlite ?

### ISSUE THREAD

**Issue by tetsuo55** [timduru/device_asus_tf_unified#6]
Hi timduru,

on the following line: https://github.com/timduru/device_asus_tf_unified/blob/katkiss-6.0/device_common.mk#L101 we have the prop persist.tegra.nvmmlite.

I did a grep of the full sourcecode and the only place i could find it was in the file linked.
Do you know anything about this command?

**Comment by timduru** [comment]
from what I remember it activates nvidia hardware multimedia libs.
It's there in stock and in recents tegra tablets like the shield too
